notion:
  api: secret_pHhIr9uzYDsgQgRccWdVBo5JMDJqeudv40cJOIWzBD0
  database_id: 24042182d0a98066a92ecfe460c534a2

# Database column mappings
database:
  task_name: 任务名称
  assignee: 负责人
  time_spent: 工作时间（分钟）
  screenshots: 截屏
  due_date: 截止日期
  status: 状态
  